Feature/initial
FlockOfBirds/star-rating pull request #3
Opened 2017-02-01 12:49 UTC by djkwagala

2017-02-02 10:40 UTC, Andries-Smit requested changes
Review code, not tests

2017-02-02 10:40 UTC, Andries-Smit commented on Gruntfile.js
> +
Add dependency check like:
https://github.com/FlockOfBirds/range-slider/blob/feature/range-slider/Gruntfile.js#L73
https://github.com/FlockOfBirds/range-slider/blob/feature/range-slider/Gruntfile.js#L82
https://github.com/FlockOfBirds/range-slider/blob/feature/range-slider/Gruntfile.js#L89

2017-02-02 10:40 UTC, Andries-Smit commented on README.md
> +* Can only rate with full star
Sum your feature, you are telling the limitation.
- Rate an object with stars

2017-02-02 10:40 UTC, Andries-Smit commented on README.md
> +* Supports half stars when rendering average rate
rendering average......
- Display average rating.
- Display rating in whole and half stars

2017-02-02 10:40 UTC, Andries-Smit commented on karma.conf.js
> +    if(config.instrumenter) {
Please use param  `codeCoverage` instead. To make it uniform across all widgets.
You already have it in the package.json

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +        if (callback) {
Add white line before `if`

2017-02-02 10:40 UTC, Andries-Smit commented on karma.conf.js
> +        reporters: [ "progress", config.instrumenter ? "coverage": "kjhtml" ],
should use param `codeCoverage`

2017-02-02 10:40 UTC, Andries-Smit commented on tslint.json
> +    // "linebreak-style": [ true, "LF" ],
comments in json file is not allowed

2017-02-02 10:40 UTC, Andries-Smit commented on tslint.json
> +  }
Add rule `"arrow-parens": false`

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +            [ this.rateAttribute, this.averageAttribute ].forEach(
inline it
```
[ this.rateAttribute, this.averageAttribute ].forEach(attribute => this.subscribe({
    attr: attribute,
    callback: () => this.updateRendering(),
    guid: this.contextObject.getGuid()
}));
```

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <enumerationValue key="single">Single</enumerationValue>
What does `Single` actual mean?
Input? Display value? Rate context object?

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Attribute where the average rate is saved</description>
Saved? Do we save averages? or display them?

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <caption>On change microflow</caption>
On change, or on vote?

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Microflow to be executed when the rate is changed</description>
Rate is changed? or rate need to store.

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/Alert.ts
> +    : null as any;
Uhmmmm? any? not needed, maybe you Typescrypt Typing needs to be changed.

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.state = { errorMessage: "" };
Add white line after calling `super`

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.fractions = 2;
Defaults do not need to be in the constructor, if need be set the in the rendering

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    private contextObject: mendix.lib.MxObject | undefined;
Do not pass the context object to your component, your wrapper should handle it.
Is is there a really good reason to it?

Ideally we splint:
wrapper => connect dojo with react (will not be needed in mx7)
wrapper => handle data interaction retreive / update data (will be replaced when plugin widgets are ready)
Component => handle business logic
Render component => handle display only

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            error: (error: Error) =>
Error typing is not needed, its defined in the mendix-client typing

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/__tests__/Alert.spec.ts
> +    it("should not render anything", () => {
Should it never render anything, or is it conditional?
"without message should not render anything"

2017-02-02 10:40 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            this.state.errorMessage = errorMessage.join("\n");
Evil code! never update state except for the constructor. Else the re-render will not be triggers. 
And don`t change your state in the rendering, that will result in loops.

Always use `setSate`
```
this.setState({
      date: new Date()
});
```

This case, we might not use `errorMessage` as state you can use private memeber

2017-02-02 10:40 UTC, Andries-Smit commented on karma.conf.js
> +        console.log("With instrumenter");
Remove the log line

2017-02-03 08:29 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.fractions = 2;
Done

2017-02-03 08:29 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            error: (error: Error) =>
Done

2017-02-03 08:30 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            this.state.errorMessage = errorMessage.join("\n");
reversed to private member

2017-02-03 08:32 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/Alert.ts
> +    : null as any;
Done.

2017-02-03 08:33 UTC, djkwagala commented on tslint.json
> +    // "linebreak-style": [ true, "LF" ],
removed

2017-02-03 08:33 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +            [ this.rateAttribute, this.averageAttribute ].forEach(
Done

2017-02-03 10:31 UTC, djkwagala commented on karma.conf.js
> +    if(config.instrumenter) {
Done

2017-02-03 10:31 UTC, djkwagala commented on karma.conf.js
> +        console.log("With instrumenter");
Done

2017-02-03 10:31 UTC, djkwagala commented on karma.conf.js
> +        reporters: [ "progress", config.instrumenter ? "coverage": "kjhtml" ],
Done

2017-02-03 10:32 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +        if (callback) {
Done

2017-02-03 10:33 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    private contextObject: mendix.lib.MxObject | undefined;
Reverted back to previous implementation, which was adhering to this convention.

2017-02-03 10:33 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.state = { errorMessage: "" };
Done

2017-02-03 11:50 UTC, djkwagala commented on Gruntfile.js
> +
Done

2017-02-03 11:50 UTC, djkwagala commented on README.md
> +* Can only rate with full star
Done

2017-02-03 11:50 UTC, djkwagala commented on README.md
> +* Supports half stars when rendering average rate
Done

2017-02-03 11:56 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <enumerationValue key="single">Single</enumerationValue>
Its for expected display behavior as in whether the widget should be used for rating or displaying a campaign's average. It requires a better name. any suggestions?

2017-02-03 12:04 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Microflow to be executed when the rate is changed</description>
Rate is changed is appropriate. The developer can choose to open another page with that rate for feedback. and may be they save from their feedback page.

2017-02-03 12:06 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <caption>On change microflow</caption>
On rate or on rate change or on change.

2017-02-03 12:07 UTC, djkwagala commented on tslint.json
> +  }
Added

2017-02-03 12:09 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Attribute where the average rate is saved</description>
`Attribute containing the average rate`

2017-02-03 14:17 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    private contextObject: mendix.lib.MxObject | undefined;
Completed

2017-02-03 14:27 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/__tests__/Alert.spec.ts
> +    it("should not render anything", () => {
Done

2017-02-03 15:08 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <enumerationValue key="single">Single</enumerationValue>
Its for expected display behavior - whether the widget should be used for rating or displaying a campaign's average. And yes, its related to the rate context object. It requires a better name. any suggestions?

2017-02-09 13:17 UTC, Andries-Smit reviewed
Still reviewing in progress.

2017-02-09 13:17 UTC, Andries-Smit commented on Gruntfile.js
> +        clean: {
Add new line

2017-02-09 13:17 UTC, Andries-Smit commented on Gruntfile.js
> +        checkDependencies: {
Add newline

2017-02-09 13:17 UTC, Andries-Smit commented on karma.conf.js
> +    if(config.codeCoverage) {
add space between if and (
`if (config.codeCoverage) {`

2017-02-09 13:17 UTC, Andries-Smit commented on package.json
> +  "description": "This widget lets users rate an object from 1 to 5",
`This widget`... please rephrase.

2017-02-09 13:17 UTC, Andries-Smit commented on package.json
> +    "grunt-check-dependencies": "^1.0.0",
`grunt-check-dependencie` is a devdependencie

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +    update(object: mendix.lib.MxObject, callback?: Function) {
`callback?: Function` better `write () => void`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +    private executeMicroflow(mendixGUID: string, microflow: string, error: (error: Error) => void) {
`mendixGUID` => `mendixGuid`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +                errorMessage.unshift("Configuration Error: ");
`return errorMessage.unshift("Configuration Error: ").join("\n") ;`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.ts
> +        return errorMessage.length ? errorMessage.join("\n") : undefined;
Remove if return is in on line 76

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +    <name>StarRating</name>
Add space `Star rating`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +    <description>This widget lets users rate an object from 1 to 5..</description>
double dots ..

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Render for rating or average</description>
=> `Render for rating or display average`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <attributeType name="Decimal"/>
Missing type `Long`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>The entity containing items which are to be rated</description>
Please explain 'containing'

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <attributeType name="Decimal"/>
Can we also support long and Integer? its just displaying... right?

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Microflow to be executed when the rate is changed</description>
Is it also triggered when the rating is made the first time?

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/Alert.ts
> +    ? DOM.div({ className: "alert alert-danger widget-star-rating-alert" }, props.message)
missing indent
```
condition
    ? expression 1
    : expression 2
```

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    ownerGUID?: string;
single capital `ownerGUID` => `ownerGuid`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.rateType = this.props.rateType;
don t like this. is has a side effect on other functions.
`const rateType = this.props.rateType;`

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    private onRate(rate: number) {
missing whiteline

2017-02-09 13:17 UTC, Andries-Smit commented on typings/react-rating.d.ts
> +        onChange?: Function,
What is the reals signature `() => void` or `(value: number) => void`
Don't use `Function`, be more specific if you can.

also for `onClick` and `onRate`

2017-02-09 13:17 UTC, Andries-Smit commented on typings/react-rating.d.ts
> +declare module 'react-rating' {
Please use "double quotes"

2017-02-09 13:17 UTC, Andries-Smit commented on typings/react.d.ts
> +    // Allow children to be null
Is this file still needed when you update to @types/react 15.0.8 ?

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            return DOM.div({ className: "widget-starrating" },
why is it `widget-starrating` other classes your uses `widget-star-rating` ?

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            this.props.handleOnChange(rate, (error: Error) => { // this function is bound to the component's context
Is this comment needed, if so. Then I dont understand

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/__tests__/Alert.spec.ts
> +    it("should not render anything", () => {
Not done! Please apply.

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/__tests__/StarRating.spec.ts
> +
Double white line

2017-02-09 13:17 UTC, Andries-Smit commented on src/com/mendix/widget/StarRating/components/__tests__/StarRating.spec.ts
> +
Remote whiteline

2017-02-09 13:17 UTC, Andries-Smit commented on tsconfig.json
> +    "skipLibCheck": true,
set once to `false` run `> tsc` to see if your typing are correct

2017-02-09 13:17 UTC, Andries-Smit commented on typings/react-rating.d.ts
> +        empty?: Array<string | Object | React.ReactElement<any>> | string | Object,
is this typing correct?

2017-02-13 08:24 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Microflow to be executed when the rate is changed</description>
yes.

2017-02-13 08:29 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <attributeType name="Decimal"/>
No, because its used for both saving the average and displaying.

2017-02-13 11:51 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>The entity containing items which are to be rated</description>
`containing` is the same as holding, bearing, carrying .....
changed to `holding`

2017-02-13 11:53 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +                <attributeType name="Decimal"/>
Done

2017-02-13 11:53 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +            <description>Render for rating or average</description>
Done

2017-02-13 11:53 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +    <description>This widget lets users rate an object from 1 to 5..</description>
Done

2017-02-13 11:53 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.xml
> +    <name>StarRating</name>
Done

2017-02-13 11:54 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +        return errorMessage.length ? errorMessage.join("\n") : undefined;
`errorMessage.unshift("Configuration Error: ")` returns a number

2017-02-13 11:54 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +                errorMessage.unshift("Configuration Error: ");
`errorMessage.unshift("Configuration Error: ")` returns a number

2017-02-13 11:54 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +    update(object: mendix.lib.MxObject, callback?: Function) {
Done

2017-02-13 11:54 UTC, djkwagala commented on package.json
> +    "grunt-check-dependencies": "^1.0.0",
Done

2017-02-13 11:54 UTC, djkwagala commented on package.json
> +  "description": "This widget lets users rate an object from 1 to 5",
` This widget is used for rating using stars `

2017-02-13 11:54 UTC, djkwagala commented on karma.conf.js
> +    if(config.codeCoverage) {
Done

2017-02-13 11:54 UTC, djkwagala commented on Gruntfile.js
> +        checkDependencies: {
Done

2017-02-13 11:54 UTC, djkwagala commented on Gruntfile.js
> +        clean: {
Done

2017-02-13 11:54 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/__tests__/Alert.spec.ts
> +    it("should not render anything", () => {
Done

2017-02-13 11:55 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +    private executeMicroflow(mendixGUID: string, microflow: string, error: (error: Error) => void) {
GUID is an abbreviation for Globally Unique Identifier. previously we had agreed to have abbreviations eg XPath. Like this.

2017-02-13 11:57 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/Alert.ts
> +    ? DOM.div({ className: "alert alert-danger widget-star-rating-alert" }, props.message)
Done

2017-02-13 12:03 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    ownerGUID?: string;
Done

2017-02-13 12:25 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.rateType = this.props.rateType;
Yes, that was the intention for its use.
no need to `const rateType` in the other functions.

2017-02-13 12:27 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +        this.rateType = this.props.rateType;
Done

2017-02-13 12:34 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +    private onRate(rate: number) {
Done

2017-02-13 12:58 UTC, djkwagala commented on typings/react-rating.d.ts
> +        empty?: Array<string | Object | React.ReactElement<any>> | string | Object,
Yes, it is correct.

2017-02-13 13:01 UTC, djkwagala commented on typings/react-rating.d.ts
> +declare module 'react-rating' {
Done

2017-02-13 13:02 UTC, djkwagala commented on src/com/mendix/widget/StarRating/components/StarRating.ts
> +            this.props.handleOnChange(rate, (error: Error) => { // this function is bound to the component's context
Removed.

2017-02-13 13:02 UTC, djkwagala commented on typings/react-rating.d.ts
> +        onChange?: Function,
Done

2017-02-14 07:17 UTC, djkwagala commented on src/com/mendix/widget/StarRating/StarRating.ts
> +    private executeMicroflow(mendixGUID: string, microflow: string, error: (error: Error) => void) {
Done

2017-05-26 05:54 UTC, Andries-Smit commented
Merged via mendixlab/master

2017-05-26 05:54 UTC, closed without merging